### ISSUE TITLE
Handle concurrent downloads of the same key

### ISSUE THREAD

**Issue by jwodder** [dandi/s3invsync#10]

**Comment by jwodder** [comment]
@yarikoptic Question: Can I rely on `s3invsync` only being run on filesystems where file locking works?

**Comment by yarikoptic** [comment]
oh. I wish I knew even for immediate case -- IIRC it is ZFS but either it is interfaced via nfs with some fancy options -- I don't know.  @satra might know more.  But why do we need locking though?  IIRC so far I think I didn't see a need.

**Comment by jwodder** [comment]
@yarikoptic Some form of locking (either internal or using the filesystem) is needed for synchronizing concurrent downloads of the same key and preventing such downloads from stepping on each other.
