### ISSUE TITLE
Look into handling of non-normalized keys

### ISSUE THREAD

**Issue by jwodder** [dandi/s3invsync#12]
Is it possible for an S3 key to be a non-normalized POSIX path, such as `foo//bar`, `foo/./bar`, or `foo/../bar`?  If so, how should `s3invsync` handle such keys?

CC @yarikoptic

**Comment by yarikoptic** [comment]
According to https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html it is impossible to upload objects starting with `../`.

Overall, I feel that it should be sufficient, at least for now to state limitation that keys must be representable as filesystem path, do the check (if normpath results in a different key) and issue a warning to catch such cases.  I think in case of dandi there should be no such cases.

**Comment by jwodder** [comment]
@yarikoptic Issue a warning and do what?  I don't think continuing to use such keys as-is is safe.
