### ISSUE TITLE
Needs memory consumption reduction

### ISSUE THREAD

**Issue by yarikoptic** [dandi/s3invsync#55]
Follow up to

- https://github.com/dandi/s3invsync/issues/54

That run of 

```
TMPDIR=$PWD/tmp RUST_BACKTRACE=1 gdb --args /home/yoh/proj/dandi/s3invsync/./target/debug/s3invsync -l DEBUG --path-filter '^zarr/aa' s3://dandiarchive/dandiarchive/dandiarchive/ dump
```

ATM, according to `top` that process is also VERY memory hungry

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                   
2870428 yoh       20   0  545.4g 543.3g 117516 t   0.0  53.9    4d+18h s3invsync 
```

free memory is still available

```shell
yoh@typhon:/mnt/DATA/data/tmp/yoh/dandi$ free -h
               total        used        free      shared  buff/cache   available
Mem:           1.0Ti       561Gi        13Gi       170Mi       438Gi       445Gi
Swap:           31Gi        28Mi        31Gi
```

**Comment by jwodder** [comment]
@yarikoptic Well, you are running a debug (non-optimized) build.  If you build with `-r`/`--release` and run the binary at `target/release/s3sinvsync` instead, things should be more efficient.  However, I believe the resulting binary will lack debug symbols, making `gdb` difficult to use.  I think you can get both optimizations and debug symbols (so long as the former doesn't mess with the latter) by adding the following to the `Cargo.toml`:

```toml
[profile.release-debug]
inherits = "release"
debug = true
```

and then passing `--profile release-debug` to `cargo build`; the resulting binary will then be at `target/release-debug/s3invsync`.

**Comment by yarikoptic** [comment]
Thanks, I will try.  

Let's just add that profile definition into `Cargo.toml` "permanently"?

Meanwhile -- I have made `/mnt/DATA/data/tmp/jwodder` on typhon so you could try when needed/desired on the same box/network/storage.

**Comment by jwodder** [comment]
@yarikoptic Profile added in #62.

**Comment by yarikoptic** [comment]
AFAIK was reported to be addressed by
- https://github.com/dandi/s3invsync/pull/64
