### ISSUE TITLE
Wishlist: more info upon general error handling

### ISSUE THREAD

**Issue by yarikoptic** [dandi/s3invsync#56]
Follow up to

- https://github.com/dandi/s3invsync/issues/54

Since multitude of logs could have flushed anything output at the beginning, it would be great if upon error and exiting, e.g. while logging `Shutting down in response to error` , we printed at least:

- which inventory manifest was processed
- version of the tool
- wallclock time it took to get there
- current memory consumption

and ideally
- some kind of a profile for memory consumption (thinking about #55 ) if feasible. Eg. how much for storing loaded manifests etc.

**Comment by jwodder** [comment]
@yarikoptic To be clear, for "current memory consumption", you want the amount of memory in use by the process at the moment the "Shutting down in response to error" message is emitted, correct?  Should that be physical memory, virtual memory, or both?

**Comment by yarikoptic** [comment]
yes -- just when shutting down for now. Both might come handy I guess.
