### ISSUE TITLE
Download objects concurrently

### ISSUE THREAD

**Issue by jwodder** [dandi/s3invsync#8]
Question for @yarikoptic: Should the inventory list CSVs be downloaded in concurrent batches as well or just be downloaded one at a time?  If they should be downloaded concurrently, should they use the same "download pool" as the objects or a separate one?

**Comment by yarikoptic** [comment]
For performance reason indeed concurrent download would be preferable.  I have no opinion on either should be the same pool or separate. I guess it would depend on implementation/available library to implement that.

**Comment by jwodder** [comment]
At the moment, I'm thinking they may have to be separate pools; otherwise, random task scheduling could give priority to the CSV downloads, preventing any object downloads from occurring until after the CSVs were finished processing.
