### ISSUE TITLE
Provide CI to build/distribute the binary

### ISSUE THREAD

**Issue by yarikoptic** [dandi/s3invsync#85]
We could then have local archive with con/tinuous like we do for git annex. 

Note that base better be the eldest Ubuntu available to guarantee better portability.

**Comment by jwodder** [comment]
@yarikoptic Do you want the CI to be triggered just for tags/GitHub releases or also for merges to `main`?  What about pushes to PRs?

**Comment by jwodder** [comment]
@yarikoptic Ping.

**Comment by jwodder** [comment]
@yarikoptic Ping.

**Comment by yarikoptic** [comment]
sorry, was busy, not following emails/alerts.  As it is being actively developed and costs us nothing (AFAIK) why not to upload artifacts with every build in master on CI (I guess eventually would be gone), i.e. upon every change in PR?  For releases, upload them as artifact(s) to release.  Again -- similarly as what we do for datalad/git-annex, so we have access to intermediate versions as well if needed.
