### ISSUE TITLE
Manage object metadata and old versions

### ISSUE THREAD

**Issue by jwodder** [dandi/s3invsync#9]
Prior discussion from https://github.com/dandi/dandi-infrastructure/issues/197:

yarikoptic:

> one possible "approach" could be
> - reflect mtime for the key from inventory in the filename mtime when generating
> - if key is the latest version -- store under original `path`
>   - store etags and versionids for keys in a folder under `.versions.json` or alike in that directory
> - when key is deleted or to be replaced with another one:
>   - read record from `.versions.json` for `{etag}` and `{versionid}` and `mv` that `{path}` to  `{path}.old.{versionid}.{etag}` (should preserve original mtime), and remove entry from `.versions.json`
>
> this way we
> - have immediate access to all the keys as on the bucket
> - could always get to desired versionId of any key (either via `.versions.json` or looking through `*.old.*` files for the path
> - do have `mtime` (stored within filesystem) so we could prune some "timed out" `*.old.* ` with a simple `find` command
> - avoid using symlinks etc - only 1 extra inode for that `.versions.json` in each folder though .

jwodder:

> > ideally we should make backup immediately usable as a "mirror" of the bucket at current point in time, but also be a true backup going back, so if something was deleted -- we still have it on local drive
>
> I assume you mean by the last part that keys deleted from the bucket should not be deleted from the backup.  What about if a key is modified — then what should happen to the old version?  What does "also be a true backup going back" mean?
>
> > reflect mtime for the key from inventory in the filename mtime when generating
>
> I don't know what you're trying to say here (First problem: filename for *what*?), and as a result I can't make sense of the rest of the source paragraph.
>
> * I'm guessing that you mean that each synced file should have its mtime set to the mtime of the source key in S3.  Furthermore, it seems that this should only be done for the purposes of pruning with `find`.  Is that correct?
> * Regarding the `.versions.json` and `{path}.old.{versionid}.{etag}` files: What if an Archive user uploads a file whose name matches one of those patterns?  For Zarr entries, at least, the resulting key in S3 would match the uploaded filename, causing problems with the backup.

yarikoptic:

> > I assume you mean by the last part that keys deleted from the bucket should not be deleted from the backup.
>
> correct!
>
> >  What about if a key is modified — then what should happen to the old version?
>
> 1. the same as if it was deleted:
>    1. `mv {path} {path}.old.{versionid}.{etag}`
>    1. remove `{path}` entry from `.versions.json`
> 1. download a new version into `{path}` and add corresponding metadata to `.versions.json`
>
>  NB. This whole design is just an idea ATM. So if you see shortcomings or have recommendations -- we can improve!
>
> > What does "also be a true backup going back" mean?
>
> Good point. Let me state it as a requirement that we should be able to identify/recover any version of any file uploaded to the archive before not just current version. ( we might later do pruning though of `.old.`s thus relaxing this requirement).
>
> > > reflect mtime for the key from inventory in the filename mtime when generating
> >
> > I don't know what you're trying to say here (First problem: filename for what?)
>
> I was trying to say that we should adjust `mtime` for the downloaded key to match `mtime` present in the inventory for it for that version, like `wget` etc do.  E.g. for the
>
> ```
> dandi@drogon:/tmp$ zcat 15a3a67a-6dec-44b6-9800-f8ddf5a44870.csv.gz  | head -n 3
> "dandiarchive","zarr/73107a2a-9eb2-47ed-be62-1feef97b8026/1/0/0/5/5/76","J_lZKtM.5fliCCeIGTmufk3R9lc_FmZg","true","false","904","2022-04-09T21:52:14.000Z","fbebe2d44529d0a25247e8b5bca5956b",
> ```
>
> we download `zarr/73107a2a-9eb2-47ed-be62-1feef97b8026/1/0/0/5/5/76` into matching path locally, from `versionId=J_lZKtM.5fliCCeIGTmufk3R9lc_FmZg` and then adjust that file `76` mtime to be `2022-04-09T21:52:14.000Z`.  This way we do not need to store mtime anywhere in e.g. `.versions.json` but would have it available as mtime of that file even when we `mv` it AFAIK.

jwodder:

> (Repeating from a recent edit to my previous comment) Regarding the `.versions.json` and `{path}.old.{versionid}.{etag} files`: What if an Archive user uploads a file whose name matches one of those patterns? For Zarr entries, at least, the resulting key in S3 would match the uploaded filename, causing problems with the backup.

yarikoptic:

> Let's
> - *minimize possibility of collision*: make `.versions.json` to become `.dandi-s3-backup-versions.json` to minimize possibility of conflict
> - *detect collision*: if `path` in received data points to `.dandi-s3-backup-versions.json` or a file matching regex of `.*\.old.{versionid_regex}.{etag_regex}` -- error out due to collision.  If we ever run into any -- we will decide what to do, e.g. to skip, obfuscate or something else.

**Comment by jwodder** [comment]
@yarikoptic Question: When a key is deleted, a no-content object with `IsDeleteMarker` set to `true` is added to the inventory list (and this object does not have an etag, though it does have a versionId).  Should such objects be represented somehow in the filesystem and/or the `.dandi-s3-backup-versions.json` file?

**Comment by yarikoptic** [comment]
I don't think we need to represent them. We just do per above

> 1. the same as if it was deleted:
>  `mv {path} {path}.old.{versionid}.{etag}`

this way we have access to prior version and there is no "current" version.  "versionId" for the DeleteMarker would be useful if we were to delete a specific DeleteMarker (there could be interleaved versioned of files with DeleteMarkers)
